added multi region support to migration-client
IBM-Cloud/kms-migration-client pull request #2
Opened 2019-01-30 23:28 UTC by gspurthi

2019-01-31 16:19 UTC, mrodden requested changes
Don't check in the binaries (*.exe) please

2019-01-31 16:27 UTC, mrodden requested changes

2019-01-31 16:27 UTC, mrodden commented on scripts/client-wrapper.sh
> +[ -n "$KP_REGION" ] && bx target -r $KP_REGION
You will want them to specify the region or just default this to "us-south" as before.

The comment you copy pasted does not make sense for region, so please remove that part.

2019-01-31 16:43 UTC, gspurthi commented on scripts/client-wrapper.sh
> +[ -n "$KP_REGION" ] && bx target -r $KP_REGION
I did not upload the envs.
Will be defining the region in envs
if the region is empty the client defaults it to us-south.

2019-01-31 16:47 UTC, gspurthi commented on scripts/client-wrapper.sh
> +[ -n "$KP_REGION" ] && bx target -r $KP_REGION
I would want them to specifiy the region if their new instance in not in us-south.

2019-01-31 21:11 UTC, ccbarragan reviewed
Just one comment @gspurthi. Otherwise LGTM.

2019-01-31 21:11 UTC, ccbarragan commented on README.md
> +    # Optional, can leave this variable blank("") if your new KeyProtect service instance is in us-south,
Some suggestions:
```suggestion
    # Optional. Set if your new Key Protect service instance is in a different region. 
    # If your new Key Protect service instance is in us-south, omit this variable. 
    #
    # Possible values: 
    # "us-east" (Washington DC) 
    # "eu-gb" (London)
    # "eu-de" (Frankfurt)
    # "au-syd" (Sydney)
    # "jp-tok" (Tokyo)
    #
    # export KP_REGION=""
```

2019-02-01 19:48 UTC, mrodden approved these changes

2019-02-01 19:48 UTC, locke105 commented on .travis.yml
> +      secure: kEDgO8W3ddFuMc0ZaPWOlFUZX0DRWE7PcGRX8tnqkxFMvV8UeUghQ9iCFh2cRJukCu6ApYvRJ45jESCLAxquoQO2OeNEnKDkxmTGgCjZcvFQtkCdyn6dewev9P9jMLRr7zkRjqfe+OouQnhnT0XmRCI3NZJJiXQjc9CoDlQ1kIAg7ACEkqVwY8iCE
This probably will not work here, since its an encrypted form of my API key for posting the releases on the other repo.

We will have to generate a new one somehow.

2019-02-01 19:51 UTC, gspurthi commented on .travis.yml
> +      secure: kEDgO8W3ddFuMc0ZaPWOlFUZX0DRWE7PcGRX8tnqkxFMvV8UeUghQ9iCFh2cRJukCu6ApYvRJ45jESCLAxquoQO2OeNEnKDkxmTGgCjZcvFQtkCdyn6dewev9P9jMLRr7zkRjqfe+OouQnhnT0XmRCI3NZJJiXQjc9CoDlQ1kIAg7ACEkqVwY8iCE
I did change the api key ,  this encrypted detail includes api key associated with my account and provides access to the IBM-CLOUD/kms-migration-client repository

2019-02-01 20:12 UTC, merged